def mk_nvt_input_fr_moltemplate(symbols,minimize,dt,dmp_step,thermo_step,md_step,T,seed,restart):
    f = open('input_nvt.lmp','w')
    f.write('# ------------------------------- Initialization Section -------------------'+'\n')
    f.write('\n')
    f.write('include "system.in.init"'+'\n')
    f.write('\n')
    f.write('# ------------------------------- Atom Definition Section -------------------'+'\n')
    f.write('\n')
    if restart:
        f.write('read_data "restart.data"'+'\n')
    else:
        f.write('read_data "system.data"'+'\n')
        f.write('\n')
        f.write('include "system.in.charges"'+'\n')
        f.write('\n')
        f.write('# ------------------------------- Settings Section --------------------------'+'\n')
        f.write('\n')
        f.write('include "system.in.settings"'+'\n')
    f.write('\n')
    f.write('# ------------------------------- Run Section -------------------------------'+'\n')
    f.write('\n')
    if not restart:
        if minimize:
            f.write('# -- minimization protocol --'+'\n')
            f.write('\n')
            f.write('minimize 1.0e-4 1.0e-6 100000 400000'+'\n')
            f.write('\n')
    f.write('# -- simulation protocol --'+'\n')
    f.write('\n')
    f.write('timestep '+str(dt)+'\n')
    f.write('\n')
    f.write('print "----------------------------------------------------------------"'+'\n')
    f.write('print "--- Run a simulation using a Nose-Hoover Thermostat ---"'+'\n')
    f.write('print "----------------------------------------------------------------"'+'\n')
    f.write('dump dmp all custom '+str(dmp_step)+' traj_nvt.lammpstrj id mol type element x y z ix iy iz'+'\n')
    f.write('dump_modify dmp element')
    for symbol in symbols:
        f.write(' '+str(symbol))
    f.write('\n')
    f.write('thermo_style custom step etotal enthalpy pe ke temp press vol density cella cellb cellc cellalpha cellbeta cellgamma'+'\n')
    f.write('thermo '+str(thermo_step)+'\n')
    f.write('\n')
    if not restart:
        f.write('velocity all create '+str(T)+' '+str(seed)+'\n')
    f.write('fix fxnvt all nvt temp '+str(T)+' '+str(T)+' $(dt*100.0)'+'\n')
    f.write('\n')
    f.write('run '+str(md_step)+'\n')
    f.write('write_data system_after_nvt.data'+'\n')
    f.close()
    
def mk_npt_input_fr_moltemplate(symbols,minimize,dt,dmp_step,thermo_step,md_step,T,P,dof_type,seed,restart):
    f = open('input_npt.lmp','w')
    f.write('# ------------------------------- Initialization Section -------------------'+'\n')
    f.write('\n')
    f.write('include "system.in.init"'+'\n')
    f.write('\n')
    f.write('# ------------------------------- Atom Definition Section -------------------'+'\n')
    f.write('\n')
    if restart:
        f.write('read_data "restart.data"'+'\n')
    else:
        f.write('read_data "system.data"'+'\n')
        f.write('\n')
        f.write('include "system.in.charges"'+'\n')
        f.write('\n')
        f.write('# ------------------------------- Settings Section --------------------------'+'\n')
        f.write('\n')
        f.write('include "system.in.settings"'+'\n')
    f.write('\n')
    f.write('# ------------------------------- Run Section -------------------------------'+'\n')
    f.write('\n')
    if not restart:
        if minimize:
            f.write('# -- minimization protocol --'+'\n')
            f.write('\n')
            f.write('minimize 1.0e-4 1.0e-6 100000 400000'+'\n')
            f.write('\n')
    f.write('# -- simulation protocol --'+'\n')
    f.write('\n')
    f.write('timestep '+str(dt)+'\n')
    f.write('\n')
    f.write('print "----------------------------------------------------------------"'+'\n')
    f.write('print "--- Run a simulation using a Nose-Hoover Thermostat/Barostat ---"'+'\n')
    f.write('print "----------------------------------------------------------------"'+'\n')
    f.write('dump dmp all custom '+str(dmp_step)+' traj_npt.lammpstrj id mol type element x y z ix iy iz'+'\n')
    f.write('dump_modify dmp element')
    for symbol in symbols:
        f.write(' '+str(symbol))
    f.write('\n')
    f.write('thermo_style custom step etotal enthalpy pe ke temp press vol density cella cellb cellc cellalpha cellbeta cellgamma'+'\n')
    f.write('thermo '+str(thermo_step)+'\n')
    f.write('\n')
    if not restart:
        f.write('velocity all create '+str(T)+' '+str(seed)+'\n')
    f.write('fix fxnpt all npt temp '+str(T)+' '+str(T)+' $(dt*100.0) '+str(dof_type)+' '+str(P)+' '+str(P)+' $(dt*1000.0)'+'\n')
    f.write('\n')
    f.write('run '+str(md_step)+'\n')
    f.write('write_data system_after_npt.data'+'\n')
    f.close()

def mk_nvtdeform_input_fr_moltemplate(symbols,minimize,dt,dmp_step,thermo_step,md_step,T,erate,tensile_step,seed,restart):
    f = open('input_nvtdeform.lmp','w')
    f.write('# ------------------------------- Initialization Section -------------------'+'\n')
    f.write('\n')
    f.write('include "system.in.init"'+'\n')
    f.write('\n')
    f.write('# ------------------------------- Atom Definition Section -------------------'+'\n')
    f.write('\n')
    if restart:
        f.write('read_data "restart.data"'+'\n')
    else:
        f.write('read_data "system.data"'+'\n')
        f.write('\n')
        f.write('include "system.in.charges"'+'\n')
        f.write('\n')
        f.write('# ------------------------------- Settings Section --------------------------'+'\n')
        f.write('\n')
        f.write('include "system.in.settings"'+'\n')
    f.write('\n')
    f.write('# ------------------------------- Run Section -------------------------------'+'\n')
    f.write('\n')
    if not restart:
        if minimize:
            f.write('# -- minimization protocol --'+'\n')
            f.write('\n')
            f.write('minimize 1.0e-4 1.0e-6 100000 400000'+'\n')
            f.write('\n')
    f.write('# -- simulation protocol --'+'\n')
    f.write('\n')
    f.write('timestep '+str(dt)+'\n')
    f.write('\n')
    f.write('print "----------------------------------------------------------------"'+'\n')
    f.write('print "--- Run a simulation using a Nose-Hoover Thermostat + Defrom---"'+'\n')
    f.write('print "----------------------------------------------------------------"'+'\n')
    f.write('dump dmp all custom '+str(dmp_step)+' traj_nvtdeform.lammpstrj id mol type element x y z ix iy iz'+'\n')
    f.write('dump_modify dmp element')
    for symbol in symbols:
        f.write(' '+str(symbol))
    f.write('\n')
    f.write('compute stressAtom all stress/atom NULL'+'\n')
    f.write('compute myStress all reduce sum c_stressAtom[3]'+'\n')
    f.write('compute pp all pressure NULL virial'+'\n')
    f.write('variable myStress equal c_myStress/vol*0.000101325'+'\n')
    f.write('variable pzz equal -1.0*c_pp[3]*0.000101325'+'\n')
    f.write('variable tmp equal "lz"'+'\n')
    f.write('variable L0 equal ${tmp}'+'\n')
    f.write('thermo_style custom step etotal enthalpy pe ke temp press vol density cella cellb cellc cellalpha cellbeta cellgamma v_myStress v_pzz'+'\n')
    f.write('thermo '+str(thermo_step)+'\n')
    f.write('\n')
    if not restart:
        f.write('velocity all create '+str(T)+' '+str(seed)+'\n')
    f.write('fix fxnvt all nvt temp '+str(T)+' '+str(T)+' $(dt*100.0)'+'\n')
    f.write('fix fxdeform all deform 1 z erate '+str(erate)+' units box remap x'+'\n')
    f.write('variable strain equal "(lz-v_L0)/v_L0"'+'\n')
    f.write('variable p1 equal "v_strain"'+'\n')
    f.write('variable p2 equal "v_myStress"'+'\n')
    f.write('variable p3 equal "v_pzz"'+'\n')
    f.write('fix fxprint all print '+str(tensile_step)+' "${p1} ${p2} ${p3}" file tensile.txt screen no'+'\n')
    f.write('\n')
    f.write('run '+str(md_step)+'\n')
    f.write('write_data system_after_nvtdeform.data'+'\n')
    f.close()

def mk_nptdeform_input_fr_moltemplate(symbols,minimize,dt,dmp_step,thermo_step,md_step,T,P,deform_style,erate,tensile_step,seed,restart):
    f = open('input_nvtdeform.lmp','w')
    f.write('# ------------------------------- Initialization Section -------------------'+'\n')
    f.write('\n')
    f.write('include "system.in.init"'+'\n')
    f.write('\n')
    f.write('# ------------------------------- Atom Definition Section -------------------'+'\n')
    f.write('\n')
    if restart:
        f.write('read_data "restart.data"'+'\n')
    else:
        f.write('read_data "system.data"'+'\n')
        f.write('\n')
        f.write('include "system.in.charges"'+'\n')
        f.write('\n')
        f.write('# ------------------------------- Settings Section --------------------------'+'\n')
        f.write('\n')
        f.write('include "system.in.settings"'+'\n')
    f.write('\n')
    f.write('# ------------------------------- Run Section -------------------------------'+'\n')
    f.write('\n')
    if not restart:
        if minimize:
            f.write('# -- minimization protocol --'+'\n')
            f.write('\n')
            f.write('minimize 1.0e-4 1.0e-6 100000 400000'+'\n')
            f.write('\n')
    f.write('# -- simulation protocol --'+'\n')
    f.write('\n')
    f.write('timestep '+str(dt)+'\n')
    f.write('\n')
    f.write('print "----------------------------------------------------------------"'+'\n')
    f.write('print "--- Run a simulation using a Nose-Hoover Thermostat/Barostat + Defrom---"'+'\n')
    f.write('print "----------------------------------------------------------------"'+'\n')
    f.write('dump dmp all custom '+str(dmp_step)+' traj_nptdeform.lammpstrj id mol type element x y z ix iy iz'+'\n')
    f.write('dump_modify dmp element')
    for symbol in symbols:
        f.write(' '+str(symbol))
    f.write('\n')
    f.write('compute stressAtom all stress/atom NULL'+'\n')
    f.write('compute myStress all reduce sum c_stressAtom[3]'+'\n')
    f.write('compute pp all pressure NULL virial'+'\n')
    f.write('variable myStress equal c_myStress/vol*0.000101325'+'\n')
    f.write('variable pzz equal -1.0*c_pp[3]*0.000101325'+'\n')
    f.write('variable tmp equal "lz"'+'\n')
    f.write('variable L0 equal ${tmp}'+'\n')
    f.write('thermo_style custom step etotal enthalpy pe ke temp press vol density cella cellb cellc cellalpha cellbeta cellgamma v_myStress v_pzz'+'\n')
    f.write('thermo '+str(thermo_step)+'\n')
    f.write('\n')
    if not restart:
        f.write('velocity all create '+str(T)+' '+str(seed)+'\n')
    if deform_style == 'semiisotropic':
        f.write('fix fxnpt all npt temp '+str(T)+' '+str(T)+' $(100.0*dt) '+'x'+' '+str(P)+' '+str(P)+' $(1000.0*dt) '+'y'+' '+str(P)+' '+str(P)+' $(1000.0*dt) '+'couple xy'+'\n')
    elif deform_style == 'anisotorpic':
        f.write('fix fxnpt all npt temp '+str(T)+' '+str(T)+' $(100.0*dt) '+'x'+' '+str(P)+' '+str(P)+' $(1000.0*dt) '+'y'+' '+str(P)+' '+str(P)+' $(1000.0*dt)'+'\n')
    f.write('fix fxdeform all deform 1 z erate '+str(erate)+' units box remap x'+'\n')
    f.write('variable strain equal "(lz-v_L0)/v_L0"'+'\n')
    f.write('variable p1 equal "v_strain"'+'\n')
    f.write('variable p2 equal "v_myStress"'+'\n')
    f.write('variable p3 equal "v_pzz"'+'\n')
    f.write('fix fxprint all print '+str(tensile_step)+' "${p1} ${p2} ${p3}" file tensile.txt screen no'+'\n')
    f.write('\n')
    f.write('run '+str(md_step)+'\n')
    f.write('write_data system_after_nptdeform.data'+'\n')
    f.close()
    